name: Supermarket Release
on:
  workflow_dispatch:

jobs:
  share:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          ref: main # requires for stove to make proper checks, otherwise git commands fail
      - uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # v1.269.0
        with:
          ruby-version: '3.0'
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
      - name: Release cookbook
        run: |
          git config --global user.email "tools@mondoo.com"
          git config --global user.name "Mondoo Tools"
          gem install stove
          mkdir -p ~/.chef
          echo ${{ secrets.SUPERMARKET_PEM }} | base64 --decode > ~/.chef/key.pem
          stove login --username ${{ secrets.SUPERMARKET_USER }} --key ~/.chef/key.pem
          git status --porcelain
          stove --log-level debug --branch main
